#!/usr/bin/env bash
# displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process
#  You cannot use pgrep
# The third line of your script must be # shellcheck

./1-list_your_processes | grep "bash"
