#!/usr/bin/env bash
# This script displays
# to infinity and beyond indefinitely
# with a sleep 2 in between each iteration
# I am invicible!!! when recieving a SIGTERM signal

trap 'echo "I am invicible!!!"' 15
while true; do
    echo "to infinity and beyond"
    sleep 2
done
